import '../app/globals.css';
import {Poppins} from 'next/font/google'
import Nav from './components/Nav'
import {TodosContextProvider} from '../app/Context/todosContext'
import {AuthContextProvider} from '../app/Context/authContext'
export const metadata = {
  title: 'todo app',
  description: 'Generated by Next.js',
}
const poppins = Poppins(
  {
     weight:['400','700'],
     subsets:['latin']
  }
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TodosContextProvider>
        <AuthContextProvider>
        <div className={poppins.className}>
          <Nav/>
        {children}</div>
        </AuthContextProvider>
        </TodosContextProvider>
        </body>
    </html>
  )
}
